

#######################
#        BUILD        #
#######################


FROM node:18.15.0-alpine AS build

WORKDIR /usr/src/app/client

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . .

CMD ["npm", "run", "build"]



#######################
#        FINAL        #
#######################


FROM scratch AS final

WORKDIR /usr/src/app/client

COPY --from=builder /usr/src/app/client/dist /dist
