version: '3.8'

services:
  
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - build_volume:/usr/src/app/client/dist
      

  core:
    container_name: core
    build:
      context: ./core
      dockerfile: Dockerfile.prod
    entrypoint: ./entrypoint.prod.sh
    command: daphne core.asgi:application -b 0.0.0.0 -p 8000
    depends_on:
      database:
        condition: service_healthy
      elastic:
        condition: service_healthy
      redis:
        condition: service_healthy
      celery:
        condition: service_healthy
    expose:
      - 8000
    volumes:
      - django_static_volume:/usr/src/app/django_static
      - django_media_volume:/usr/src/app/django_media
    env_file:
      - ./env_files/core/.prod.env
  
  
  database:
    container_name: database
    image: postgres:15-alpine
    expose:
      - 5432
    volumes:
      - database_volume:/var/lib/postgresql/data
    env_file:
      - ./env_files/database/.prod.env
    healthcheck:
      test: pg_isready
      interval: 30s
      timeout: 10s
      retries: 5
      
      
  redis:
    container_name: redis
    image: redis:7-alpine
    expose:
      - 6379
    command: redis-server /usr/local/etc/redis/redis.prod.conf
    volumes:
      - ./redis/redis.prod.conf:/usr/local/etc/redis/redis.prod.conf
    healthcheck:
      test: redis-cli -a $REDIS_PASSWORD --raw incr ping
      interval: 30s
      timeout: 10s
      retries: 5
      
  
  celery:
    container_name: celery
    build:
      context: ./core
      dockerfile: Dockerfile.prod
    command: celery -A core.celery_app worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - celery_logs:/usr/src/app/logs
      - django_media_volume:/usr/src/app/django_media
    env_file:
      - ./env_files/core/.prod.env
      - ./env_files/celery/.prod.env
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: celery -A core.celery_app inspect ping
      interval: 30s
      timeout: 10s
      retries: 5
      
   
  flower:
    container_name: flower
    build:
      context: ./core
      dockerfile: Dockerfile.prod
    command: celery -A core.celery_app flower --port=5555 --url-prefix=flower
    expose:
      - 5555
    env_file:
      - ./env_files/core/.prod.env
      - ./env_files/flower/.prod.env
    depends_on:
      redis:
        condition: service_healthy
      celery:
        condition: service_healthy
      
      
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - django_static_volume:/usr/src/app/django_static
      - django_media_volume:/usr/src/app/django_media
      - build_volume:/usr/src/app/build
    depends_on:
      - core
      - client
      
      
  elastic:
    container_name: elastic
    image: elasticsearch:7.14.0
    expose:
      - 9200
    environment:
        - "bootstrap.memory_lock=true"
        - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    env_file:
      - ./env_files/elastic/.prod.env
    healthcheck:
      test: curl -s http://elastic:$ELASTIC_PASSWORD@elastic:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 10
      
    
volumes:
  database_volume:
  celery_logs:
  django_static_volume:
  django_media_volume:
  build_volume:
  