# Generated by Django 4.2.3 on 2023-08-15 12:44

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True)),
                ('icon', models.ImageField(default=chat.models.random_group_icon, upload_to='')),
                ('wall_image', models.ImageField(default=chat.models.random_user_wallpaper, upload_to='')),
                ('category', models.CharField(choices=[('Gaming', 'Gaming'), ('Music', 'Music'), ('Education', 'Education'), ('Science', 'Science'), ('Entertainment', 'Entertainment'), ('Undefined', 'Undefined')], default='Undefined', max_length=35)),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('invite_in_group', 'Can send invites to group'), ('assign_roles_in_group', 'Can assign group roles')),
            },
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group')),
            ],
            options={
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('is_hidden', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.message')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.grouprole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='home', max_length=22)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=45)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Attack Helicopter', 'Attack Helicopter'), ('Undefined', 'Undefined')], default='Undefined', max_length=35)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('date_last_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('icon', models.ImageField(default=chat.models.random_user_icon, upload_to='')),
                ('wallpaper', models.ImageField(default=chat.models.random_user_wallpaper, upload_to='')),
                ('is_online', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Sleeping', 'Sleeping'), ('Busy', 'Busy')], default='Offline', max_length=35)),
                ('default_status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Sleeping', 'Sleeping'), ('Busy', 'Busy')], default='Online', max_length=35)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=22)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group')),
            ],
            options={
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.message')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.participant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
            options={
                'unique_together': {('participant', 'room')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(through='chat.RoomParticipant', to='chat.participant'),
        ),
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.topic'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(through='chat.Participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('topic', 'name')},
        ),
    ]
