# Generated by Django 4.2.3 on 2023-08-27 14:00

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(default=chat.models.random_user_icon, upload_to='user_icons'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallpaper',
            field=models.ImageField(default=chat.models.random_user_wallpaper, upload_to='user_wallpapers'),
        ),
    ]
