

#######################
#        BUILD        #
#######################


FROM python:3.10-slim-buster as BUILDER

WORKDIR /usr/src/app/core

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
 apt-get install -y --no-install-recommends gcc postgresql

RUN pip install --upgrade pip

COPY ./requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/core/wheels -r requirements.txt



#######################
#        FINAL        #
#######################


FROM python:3.10-slim-buster AS final

WORKDIR /usr/src/app/core

COPY . .

COPY --from=builder /usr/src/app/core/wheels /wheels
COPY --from=builder /usr/src/app/core/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache /wheels/*

RUN sed -i 's/\r$//g' entrypoint.dev.sh
RUN chmod +x entrypoint.dev.sh
