# Generated by Django 4.2.3 on 2023-07-29 21:06

import chatauth.validators.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatauth', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. Must contain from 5 to 45 characters.Not shorter than 5 characters. Letters, digits and -/_ only.', max_length=45, unique=True, validators=[
                chatauth.validators.validators.SlugUsernameValidator(), django.core.validators.MinLengthValidator(5)], verbose_name='username'),
        ),
    ]
